const { google } = require('googleapis');
const Meeting = require('../models/Meeting');

class MeetService {
  constructor() {
    // Initialize Google Calendar API with service account
    this.auth = new google.auth.JWT(
      process.env.GOOGLE_CLIENT_EMAIL,
      null,
      process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
      ['https://www.googleapis.com/auth/calendar']
    );
    this.calendar = google.calendar({ version: 'v3', auth: this.auth });
  }

  // 🆕 PROPER GOOGLE MEET CREATION USING CALENDAR API
  async createMeeting(adminId, title, description, adminName) {
    try {
      console.log('🎯 Creating Google Meet via Calendar API...');

      const event = {
        summary: title || 'The Conclave Academy Live Stream',
        description: description || 'Join our community training session',
        start: {
          dateTime: new Date().toISOString(),
          timeZone: 'Africa/Lagos',
        },
        end: {
          dateTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(), // 2 hours
          timeZone: 'Africa/Lagos',
        },
        conferenceData: {
          createRequest: {
            requestId: `meet-${Date.now()}-${Math.random().toString(36).substring(7)}`,
            conferenceSolutionKey: { type: 'hangoutsMeet' },
          },
        },
        // 🆕 CRITICAL SETTINGS FOR SEAMLESS JOINING
        anyoneCanAddSelf: true,
        guestsCanInviteOthers: true,
        guestsCanSeeOtherGuests: true,
        guestsCanModify: false,
        transparency: 'transparent',
        visibility: 'public',
      };

      console.log('📅 Creating Google Calendar event...');
      const response = await this.calendar.events.insert({
        calendarId: 'primary',
        resource: event,
        conferenceDataVersion: 1,
        sendUpdates: 'none',
      });

      if (!response.data.hangoutLink) {
        throw new Error('No Google Meet link generated by Calendar API');
      }

      console.log('✅ Google Calendar event created:', response.data.htmlLink);

      // Extract meeting code from the actual Google Meet link
      const meetingCode = this.extractMeetingCode(response.data.hangoutLink);
      
      if (!meetingCode) {
        throw new Error('Could not extract valid meeting code from Google Meet link');
      }

      // 🆕 CREATE PROPER JOIN LINKS
      const directJoinLink = `https://meet.google.com/${meetingCode}`;
      const instantJoinLink = `https://meet.google.com/${meetingCode}?authuser=0`;

      console.log('🔗 Generated meeting links:', {
        hangoutLink: response.data.hangoutLink,
        meetingCode: meetingCode,
        directJoinLink: directJoinLink
      });

      // Save to database
      const meeting = new Meeting({
        meetingId: response.data.id,
        meetLink: response.data.hangoutLink,
        directJoinLink: directJoinLink,
        instantJoinLink: instantJoinLink,
        meetingCode: meetingCode,
        title: title || 'The Conclave Academy Live Stream',
        description: description || 'Join our community training session',
        createdBy: adminId,
        adminName: adminName || 'The Conclave Academy',
        scheduledStart: new Date(),
        scheduledEnd: new Date(Date.now() + 2 * 60 * 60 * 1000),
        status: 'active',
        googleEventId: response.data.id,
        hangoutLink: response.data.hangoutLink,
        settings: {
          anyoneCanJoin: true,
          requiresAuthentication: false,
          canJoinBeforeHost: true,
          knockRequired: false,
          seamlessJoinEnabled: true
        }
      });

      await meeting.save();

      console.log('✅ Meeting created successfully with Google Calendar API');

      return {
        success: true,
        meeting: meeting,
        meetingLink: response.data.hangoutLink,
        directJoinLink: directJoinLink,
        instantJoinLink: instantJoinLink,
        meetingCode: meetingCode,
        googleEventId: response.data.id
      };

    } catch (error) {
      console.error('❌ Error creating Google Meet via Calendar API:', error);
      
      // 🆕 FALLBACK: CREATE SIMPLE MEETING WITHOUT GOOGLE API
      if (error.code === 403 || error.message.includes('permission')) {
        console.log('🔄 Falling back to simple meeting creation...');
        return await this.createSimpleMeeting(adminId, title, description, adminName);
      }
      
      return { 
        success: false, 
        error: error.message,
        details: 'Failed to create Google Meet via Calendar API'
      };
    }
  }

  // 🆕 FALLBACK METHOD FOR SIMPLE MEETING CREATION
  async createSimpleMeeting(adminId, title, description, adminName) {
    try {
      console.log('🔄 Creating simple meeting (fallback mode)...');
      
      // Generate a valid Google Meet-like code
      const meetingCode = this.generateValidMeetCode();
      const meetLink = `https://meet.google.com/${meetingCode}`;
      const directJoinLink = `https://meet.google.com/${meetingCode}`;
      const instantJoinLink = `https://meet.google.com/${meetingCode}?authuser=0`;

      const meeting = new Meeting({
        meetingId: `simple_${Date.now()}_${Math.random().toString(36).substring(7)}`,
        meetLink: meetLink,
        directJoinLink: directJoinLink,
        instantJoinLink: instantJoinLink,
        meetingCode: meetingCode,
        title: title || 'The Conclave Academy Live Stream',
        description: description || 'Join our community training session',
        createdBy: adminId,
        adminName: adminName || 'The Conclave Academy',
        scheduledStart: new Date(),
        scheduledEnd: new Date(Date.now() + 2 * 60 * 60 * 1000),
        status: 'active',
        settings: {
          anyoneCanJoin: true,
          requiresAuthentication: false,
          canJoinBeforeHost: true,
          knockRequired: false,
          seamlessJoinEnabled: true
        }
      });

      await meeting.save();

      console.log('✅ Simple meeting created (fallback):', meetingCode);

      return {
        success: true,
        meeting: meeting,
        meetingLink: meetLink,
        directJoinLink: directJoinLink,
        instantJoinLink: instantJoinLink,
        meetingCode: meetingCode,
        fallback: true,
        message: 'Meeting created using fallback method'
      };

    } catch (error) {
      console.error('❌ Error in fallback meeting creation:', error);
      return { 
        success: false, 
        error: error.message,
        details: 'Failed to create meeting even with fallback'
      };
    }
  }

  // 🆕 IMPROVED MEETING CODE EXTRACTION
  extractMeetingCode(meetingLink) {
    if (!meetingLink) return null;
    
    console.log('🔍 Extracting meeting code from:', meetingLink);
    
    // Handle different Google Meet URL formats
    const patterns = [
      /meet\.google\.com\/([a-z]{3}-[a-z]{4}-[a-z]{3})/i,  // abc-defg-hij
      /meet\.google\.com\/([a-z]+-[a-z]+-[a-z]+)/i,        // any format with dashes
      /meet\.google\.com\/([a-zA-Z0-9-]+)/,               // any alphanumeric with dashes
      /\/_meet\/([a-zA-Z0-9-]+)/                          // _meet format
    ];
    
    for (let pattern of patterns) {
      const match = meetingLink.match(pattern);
      if (match && match[1]) {
        console.log('✅ Extracted meeting code:', match[1]);
        return match[1];
      }
    }
    
    console.log('❌ Could not extract meeting code from link');
    return null;
  }

  // 🆕 GENERATE VALID GOOGLE MEET-LIKE CODE
  generateValidMeetCode() {
    const adjectives = ['quick', 'bright', 'clear', 'happy', 'smart', 'brave', 'calm', 'eager', 'fancy', 'gentle'];
    const nouns = ['lion', 'tiger', 'eagle', 'ocean', 'river', 'forest', 'mountain', 'valley', 'desert', 'island'];
    
    const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
    const noun = nouns[Math.floor(Math.random() * nouns.length)];
    const num = Math.floor(Math.random() * 900) + 100; // 100-999
    
    return `${adj}-${noun}-${num}`;
  }

  // 🆕 GET ENHANCED MEETING INFO
  async getActiveMeeting() {
    try {
      const meeting = await Meeting.findOne({ 
        status: 'active',
        scheduledEnd: { $gt: new Date() }
      }).sort({ scheduledStart: -1 });

      if (!meeting) {
        return { success: false, message: 'No active meeting found' };
      }

      // 🆕 ENSURE MEETING HAS ALL REQUIRED LINKS
      const enhancedMeeting = {
        ...meeting.toObject(),
        directJoinLink: meeting.directJoinLink || `https://meet.google.com/${meeting.meetingCode}`,
        instantJoinLink: meeting.instantJoinLink || `https://meet.google.com/${meeting.meetingCode}?authuser=0`,
        // 🆕 ADD COMPATIBILITY WITH EXISTING FRONTEND
        meetingLink: meeting.meetLink || meeting.directJoinLink,
        adminId: meeting.createdBy,
        adminName: meeting.adminName,
        startTime: meeting.scheduledStart,
        endTime: meeting.scheduledEnd,
        participants: meeting.participants || []
      };

      return {
        success: true,
        meeting: enhancedMeeting
      };
    } catch (error) {
      console.error('Error getting active meeting:', error);
      return { success: false, error: error.message };
    }
  }

  // 🆕 ENHANCED JOIN MEETING
  async joinMeeting(meetingId, userId, userName) {
    try {
      const meeting = await Meeting.findById(meetingId);
      if (!meeting) {
        return { success: false, error: 'Meeting not found' };
      }

      // Add participant
      if (!meeting.participants) {
        meeting.participants = [];
      }

      const existingParticipant = meeting.participants.find(p => 
        p.userId && p.userId.toString() === userId.toString() && !p.leftAt
      );
      
      if (!existingParticipant) {
        meeting.participants.push({
          userId,
          userName: userName || 'Participant',
          joinedAt: new Date(),
          joinMethod: 'seamless'
        });
        meeting.participantCount = meeting.participants.filter(p => !p.leftAt).length;
        await meeting.save();
      }

      // 🆕 RETURN ALL POSSIBLE JOIN LINKS
      const joinLinks = {
        primary: meeting.meetLink,
        direct: meeting.directJoinLink || `https://meet.google.com/${meeting.meetingCode}`,
        instant: meeting.instantJoinLink || `https://meet.google.com/${meeting.meetingCode}?authuser=0`,
        fallback: meeting.meetLink
      };

      console.log('🔗 Generated join links:', joinLinks);

      return {
        success: true,
        joinLinks: joinLinks,
        message: 'Join links generated successfully'
      };

    } catch (error) {
      console.error('Error joining meeting:', error);
      return { success: false, error: error.message };
    }
  }

  // EXTEND MEETING
  async extendMeeting(meetingId, adminId) {
    try {
      const meeting = await Meeting.findById(meetingId);
      if (!meeting) {
        return { success: false, error: 'Meeting not found' };
      }

      if (meeting.createdBy.toString() !== adminId.toString()) {
        return { success: false, error: 'Only meeting admin can extend meeting' };
      }

      // Extend by 1 hour
      const newEndTime = new Date(meeting.scheduledEnd.getTime() + 60 * 60 * 1000);
      meeting.scheduledEnd = newEndTime;
      meeting.extensions = (meeting.extensions || 0) + 1;
      meeting.lastExtensionAt = new Date();
      await meeting.save();

      return {
        success: true,
        meeting: meeting,
        message: 'Meeting extended successfully'
      };
    } catch (error) {
      console.error('Error extending meeting:', error);
      return { success: false, error: error.message };
    }
  }

  // END MEETING
  async endMeeting(meetingId, adminId) {
    try {
      const meeting = await Meeting.findById(meetingId);
      if (!meeting) {
        return { success: false, error: 'Meeting not found' };
      }

      if (meeting.createdBy.toString() !== adminId.toString()) {
        return { success: false, error: 'Only meeting admin can end meeting' };
      }

      meeting.status = 'ended';
      meeting.actualEnd = new Date();
      await meeting.save();

      return {
        success: true,
        message: 'Meeting ended successfully'
      };
    } catch (error) {
      console.error('Error ending meeting:', error);
      return { success: false, error: error.message };
    }
  }

  // CLEAR ALL MEETINGS
  async clearAllMeetings() {
    try {
      console.log('🧹 Clearing all meetings...');
      
      // End all active meetings
      await Meeting.updateMany(
        { status: 'active' },
        { 
          status: 'ended',
          actualEnd: new Date()
        }
      );

      console.log('✅ All meetings cleared successfully');
      return {
        success: true,
        message: 'All meetings cleared successfully'
      };
    } catch (error) {
      console.error('❌ Error clearing meetings:', error);
      return { 
        success: false, 
        error: error.message 
      };
    }
  }

  // GET MEETING BY ID
  async getMeetingById(meetingId) {
    try {
      const meeting = await Meeting.findById(meetingId);
      if (!meeting) {
        return { success: false, error: 'Meeting not found' };
      }

      return {
        success: true,
        meeting: meeting
      };
    } catch (error) {
      console.error('Error getting meeting:', error);
      return { success: false, error: error.message };
    }
  }

  // GET ALL MEETINGS (for admin)
  async getAllMeetings() {
    try {
      const meetings = await Meeting.find().sort({ scheduledStart: -1 });
      return {
        success: true,
        meetings: meetings
      };
    } catch (error) {
      console.error('Error getting all meetings:', error);
      return { success: false, error: error.message };
    }
  }
}

module.exports = new MeetService();